services:
  database-postgres:
    container_name: project-houdini-db-postgres
    profiles:
      - dev
      - db
    env_file:
      - environment.env
    image: postgres
    networks:
      backend-database: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magician"]
      interval: 1s
      retries: 30
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/postgresql.conf:/etc/postgresql.conf
  nextjs:
    container_name: project-houdini-nextjs
    build:
      context: ./nextjs
      target: dev
    profiles:
      - dev
    networks:
      backend-database: null
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./nextjs:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  migrations:
    image: liquibase/liquibase
    container_name: project-houdini-liquibase
    profiles:
      - migrations
    depends_on:
      database-postgres:
        condition: service_healthy
    volumes:
      - ./liquibase:/liquibase/changelog
    networks:
      backend-database: null
    command: --defaults-file=/liquibase/changelog/liquibase.docker.properties update
networks:
  backend-database: {}
