services:
  backend-fastapi:
    build:
      context: ./backend
    container_name: project-houdini-backend-fastapi
    profiles:
      - backend
      - dev
    env_file:
      - environment.env
    volumes:
      - ./backend:/code
    depends_on:
      database-postgres:
        condition: service_healthy
    networks:
      backend-database: null
    ports:
      - mode: ingress
        target: 80
        published: "81"
        protocol: tcp
    restart: always
  database-postgres:
    container_name: project-houdini-db-postgres
    profiles:
      - backend
      - dev
    env_file:
      - environment.env
    image: postgres
    networks:
      backend-database: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magician"]
      interval: 1s
      retries: 30
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/postgresql.conf:/etc/postgresql.conf
  vite-react:
    build:
      context: ./frontend
      args:
        ENV: dev
    container_name: project-houdini-frontend-react
    profiles:
      - dev
      - frontend
    env_file:
      - environment.env
    networks:
      backend-database: null
    # depends_on:
    #   backend-fastapi:
    #     condition: service_started
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
    volumes:
      - ./frontend:/app/
      - /app/node_modules/
  vite-react-production:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    container_name: project-houdini-frontend-react-production
    profiles:
      - prod
    env_file:
      - environment.env
    networks:
      backend-database: null
    # depends_on:
    #   backend-fastapi:
    #     condition: service_started
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
  # volumes:
  #   - ./frontend:/app/
  #   - /app/node_modules/
networks:
  backend-database: {}
